#ifndef RNET_DEFINITIONS_HPP
#define RNET_DEFINITIONS_HPP

/* RNET COMMUNICATION DEFINITIONS */
#define RNETCOMM_ACKTIMEOUT			50 // ms

/* RNET PACKET DEFINITIONS */
#define RNETPACKET_SIZE_HEADER		4
#define RNETPACKET_SYN_DEFAULT      0x55
#define RNETPACKET_STARTUP_FLAG		1
#define RNETPACKET_STARTUP_MESSAGE	0x1
#define RNETPACKET_STARTUP_SIZE		1

// Checksum values
#define CHECKSUM_CRC16_INIT_VALUE	0xFFFFu
#define CHECKSUM_CRC16_POLY			0x90D9u
#define CHECKSUM_CRC8_INIT_VALUE	0xFFu
#define CHECKSUM_CRC8_POLY			0x2Fu

#endif
