#ifndef RNET_DEFINITIONS_HPP
#define RNET_DEFINITIONS_HPP



/* RNET PACKET DEFINITIONS */
#define RNETPACKET_SIZE_HEADER		4
#define RNETPACKET_SYN_DEFAULT      0x55

// Checksum values
#define CHECKSUM_CRC16_INIT_VALUE	0xFFFFu
#define CHECKSUM_CRC16_POLY			0x90D9u
#define CHECKSUM_CRC8_INIT_VALUE	0xFFu
#define CHECKSUM_CRC8_POLY			0x2Fu

#endif
